# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000
unsetopt beep nomatch
setopt histignorespace
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

PS1="%F{blue}%n%f %F{green}%~%f %% "
alias ls='ls --color=auto'
alias grep='grep --color=auto'

mkcd() {
    if [[ -n "$1" ]]; then
	mkdir -p "$1"
	cd "$1"
    fi
}

. ~/.profile
